Performing system checks...

Graph_dict --->>> {'company': 'usecase', 'technology_focus': 'company', 'engagement_details': 'company', 'venture_capitalist': 'company', 'vertical': 'company', 'feedback': 'zensar_customer', 'usecase': 'zensar_customer', 'zensar_customer': 'feedback', 'active_customers': 'company'}
System check identified no issues (0 silenced).
May 29, 2024 - 16:57:55
Django version 3.2.4, using settings 'lucenePoc.settings'
Starting development server at http://0.0.0.0:8877/
Quit the server with CONTROL-C.
